// Copyright 2022, the Chromium project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSr5RtlBZ4mSkZUmvnSfEQbCNLUuc8zns',
    appId: '1:604928870549:android:3517964cc01563a7af739c',
    messagingSenderId: '604928870549',
    projectId: 'padadeliveryapp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB75a4Gh9NqrFMKngNf19ouiuNzdMd-5DQ',//'AIzaSyCSr5RtlBZ4mSkZUmvnSfEQbCNLUuc8zns',
    appId: '1:604928870549:ios:a0fa84b28cddf893af739c',
    messagingSenderId: '604928870549',
    projectId: 'padadeliveryapp',
    androidClientId:
        '604928870549-ea0te47k4ivm7i9lfftamofr9h12re24.apps.googleusercontent.com',
    iosClientId:
        '604928870549-r2fglbbialqvsfv50tfvf10vat7bedq5.apps.googleusercontent.com',
    // '406099696497-irb7edfevfkhi6t5s9kbuq1mt1og95rg.apps.googleusercontent.com',
    iosBundleId: 'com.pada.deliverapp',
  );
}
